This script simulates a game of battleships. It creates an n x n grid and asks the player to input their ship positions into the grid. It then asks the user to select a tile and tells the user if the tile was a hit or a miss.

This script uses numpy, string and re packages that are imported. Numpy is to work with arrays, string is to generate an alphabet string, and re is for regex validation.

In [5]:
# importing numpy
import numpy as np
# importing string to generate an alphabet string
import string
# importing regex for input validation
import re

This part of the script is where the user selects their boat positions. It asks the user to select their boat position and orientation out of the pre-defined boats allows (two 1's, two 2's and a 3). It only stops once all the boats have been placed in eligible positions. It does not allow co-ordinates that are invalid, either because they aren't allowed or the boat would be out of bounds or where another boat is.

In [6]:
# Creating a 5 x 5 grid. This will be a list of 5 zeroes, added to a list 5 times. This simulates a 5 x 5 grid.
n = 9
board = np.zeros((n,n))
# using an alphabet string to convert letter input into index value
alphabet = string.ascii_uppercase
# allowing boats of different sizes (starting with a 1 and 2)
boats = [1,1,2,2,3]
# set the number of boats to be selected
no_of_boats = len(boats)
# getting the user to select the 3 positions for the boat
boat_counter = 0
while boat_counter < no_of_boats:
    # specifying the current boat
    current_boat = boats[boat_counter]
    if current_boat != 1:
        # getting the user to specify the boat orientation
        boat_orientation = input("Please choose whether to put the boat horizontally (1) or vertically (2)")
        # validating the input to ensure that it does not break
        while not re.match("\\b[1-2]\\b",str(boat_orientation)):
            print('Please select 1 for horizontal or 2 for vertical')
            boat_orientation = input("Please choose whether to put the boat horizontally (1) or vertically (2)")
    else: boat_orientation = 1
    # getting the user to specify the position of each boat
    boat_position = input("Please enter the co-ordinates of boat " + str(boat_counter+1) + " of size " + str(boats[boat_counter]) + ". For example, enter A1 for the top left voxel.").upper()
    boat_valiation = "[A-" + str(alphabet[n-1].upper()) + "]{1}[1-" +str(n) + "]{1}"
    # validating the input
    while not re.match(boat_valiation,boat_position):
        print("Ensure that your co-ordinates are in the form A1, where the first character is between A and " + alphabet[n-1] +" and the second is between 1 and " + str(n))
        boat_position = input("Please enter the position of boat " + str(boat_counter+1) + " of size " + str(boats[boat_counter]) + ". For example, enter A1 for the top left voxel.").upper()
    boat_position_y = boat_position[0]
    boat_position_x = boat_position[1]
    #boat_position_y = input("Please enter the y co-ordinate of boat " + str(boat_counter + 1) + " between A and " + alphabet[n-1] +":").upper()
    #boat_position_x = input("Please enter the x co-ordinate of boat " + str(boat_counter + 1) + " between 1 and " + str(n) +":")
    # calculating the first and last index values of the boat
    boat_position_x1 = int(boat_position_x) - 1
    boat_position_y1 = alphabet.index(boat_position_y)
    if int(boat_orientation) == 1:
        boat_position_x2 = boat_position_x1 + current_boat - 1
        boat_position_y2 = boat_position_y1
    else:
        boat_position_x2 = boat_position_x1
        boat_position_y2 = boat_position_y1 + current_boat - 1
    # first checking that the boat is in bounds
    if boat_position_x2 > n - 1 or boat_position_y2 > n - 1 :
        print("The boat is out of the boundary of the board.")
    # checking if the boat is going to clash with another boat
    elif 1 in board[boat_position_y1:boat_position_y2+1][boat_position_x1:boat_position_x2+1]:
        print("There is already a boat at that position")
    # if the choice is empty, place the boat in that place and increase the boat counter. Otherwise, prompt the user to select again
    else:
        if int(boat_orientation) == 1:
            board[boat_position_y1][boat_position_x1:boat_position_x2+1] = 1
        else:
            for row in range(boat_position_y1,boat_position_y2+1):
                board[row][boat_position_x1] = 1
        boat_counter += 1
print(board)

[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


This part of the script is for the user to take attempts to hit a boat. Like the above, if the input is invalid then the user needs to select the co-ordinates again. The script only ends when all boats have been destroyed.

In [8]:
# get the user to select a square and see if it is a hit
hit_counter = 0
turn_counter = 0
while hit_counter < sum(boats):
    # getting the user to specify the position of a strike
    boat_position = input("Please enter the co-ordinates that you would like to hit where the first character is between A and " + alphabet[n-1] +" and the second is between 1 and " + str(n)).upper()
    # validating the input
    while not re.match(boat_valiation,boat_position):
        print("Ensure that your co-ordinates are in the form A1, where the first character is between A and " + alphabet[n-1] +" and the second is between 1 and " + str(n))
        boat_position = input("Please enter the co-ordinates that you would like to hit where the first character is between A and " + alphabet[n-1] +" and the second is between 1 and " + str(n)).upper()
    boat_position_y = boat_position[0]
    boat_position_x = boat_position[1]
    # converting to index values
    boat_position_x_int = int(boat_position_x) - 1
    boat_position_y_int = alphabet.index(boat_position_y)
    # outputting the appropriate message when a chice is made. If a hit is made, increase the hit counter.
    if board[boat_position_y_int][boat_position_x_int] == 1:
        print("You hit a boat!")
        hit_counter += 1
        board[boat_position_y_int][boat_position_x_int] = 2
    elif board[boat_position_y_int][boat_position_x_int] == 2:
        print("You already hit that square.")
    elif board[boat_position_y_int][boat_position_x_int] == 0:
        print("You missed.")
        board[boat_position_y_int][boat_position_x_int] = 2
    turn_counter += 1

print("You won! You destroyed all of the ships in " + str(turn_counter) + " turns.")

You hit a boat!
You hit a boat!
You hit a boat!
You hit a boat!
You won! You destroyed all of the ships in 4 turns.
